apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.controller.type: daemonset
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: lms-runner
  name: lms-runner
spec:
  selector:
    matchLabels:
      io.kompose.service: lms-runner
  template:
    metadata:
      labels:
        io.kompose.service: lms-runner
    spec:
      containers:
        - image: harbor.alie.javeriana.edu.co/images/lms-runner:latest
          name: lms-runner
          ports:
            - containerPort: 5900
              protocol: TCP
            - containerPort: 1234
              protocol: TCP
          env:
            - name: GPU_OFFLOAD
              value: "0.828"
          livenessProbe:
            exec:
              command:
                - bash
                - /app/health.sh
            initialDelaySeconds: 60
            periodSeconds: 2
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Always
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
