apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.controller.type: daemonset
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: lms-runner
  name: lms-runner
spec:
  ports:
    - name: "5900"
      port: 5900
      targetPort: 5900
    - name: "1234"
      port: 1234
      targetPort: 1234
  selector:
    io.kompose.service: lms-runner
